"""add whatsapp message log table

Revision ID: 13aacd383e2d
Revises: 28b92f4c8e2b
Create Date: 2026-09-19 12:46:33.803876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aacd383e2d'
down_revision = '28b92f4c8e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_message_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_sid', sa.String(length=64), nullable=False),
    sa.Column('from_number_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', name='whatsapp_status_enum'), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid', name='uq_whatsapp_message_sid')
    )
    with op.batch_alter_table('whatsapp_message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_message_logs_from_number_hash'), ['from_number_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_message_logs_message_sid'), ['message_sid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_logs_message_sid'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_logs_from_number_hash'))

    op.drop_table('whatsapp_message_logs')
    # ### end Alembic commands ###
