"""add citizen account region_id and locality

Revision ID: 28b92f4c8e2b
Revises: 572440b91f38
Create Date: 2026-09-19 12:26:31.955309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b92f4c8e2b'
down_revision = '572440b91f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('locality', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(None, 'administrative_regions', ['region_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('locality')
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
