"""add account_sessions and is_demo flags

Revision ID: 2f052fe57b62
Revises: 1759475118ab
Create Date: 2026-09-13 15:13:14.581417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f052fe57b62'
down_revision = '1759475118ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.Enum('citizen', 'government', name='session_account_type_enum'), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sessions_token_hash'), ['token_hash'], unique=True)

    # server_default=false is required here: citizen_accounts and
    # government_accounts already have real rows (3 + 10 respectively —
    # see app/models/auth_models.py provenance note), so a NOT NULL column
    # added without a default would fail against existing data. seed_data.py
    # separately flips the 13 known demo accounts to is_demo=True.
    with op.batch_alter_table('citizen_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('government_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('citizen_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_account_sessions_account_id'))

    op.drop_table('account_sessions')
    # ### end Alembic commands ###
