"""add report problem_summary_en common-format field

Revision ID: 572440b91f38
Revises: 6bd53d896b19
Create Date: 2026-09-13 15:57:26.867737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572440b91f38'
down_revision = '6bd53d896b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_summary_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('problem_summary_en')

    # ### end Alembic commands ###
