"""initial schema

Revision ID: 64d29c027862
Revises: 
Create Date: 2026-08-22 04:03:28.933420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d29c027862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('supported_languages', sa.Text(), nullable=False),
    sa.Column('administrative_hierarchy_adapter', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('administrative_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('national', 'state_province', 'district_municipality', 'constituency', name='region_level_enum'), nullable=False),
    sa.Column('parent_region_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['parent_region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_ids', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('centroid_wkt', sa.Text(), nullable=True),
    sa.Column('affected_localities', sa.JSON(), nullable=True),
    sa.Column('trend', sa.Enum('stable', 'increasing', 'decreasing', name='trend_enum'), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='cluster_confidence_enum'), nullable=False),
    sa.Column('active_status', sa.Enum('Active', 'UnderGovernmentReview', 'Deferred', 'Deprioritized', 'ActionTaken', 'Resolved', name='cluster_active_status_enum'), nullable=False),
    sa.Column('review_status', sa.Enum('NotReviewed', 'PendingValidation', 'UnderReview', 'Decided', name='cluster_review_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demographic_data_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('population_affected', sa.Integer(), nullable=True),
    sa.Column('population_total', sa.Integer(), nullable=True),
    sa.Column('demographic_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_last_updated', sa.Date(), nullable=True),
    sa.Column('platform_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_period', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'needs_review', name='demo_verification_enum'), nullable=False),
    sa.Column('freshness_status', sa.Enum('recent', 'stale', 'unknown', name='demo_freshness_enum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demographic_data_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demographic_data_points_country_id'), ['country_id'], unique=False)

    op.create_table('government_investments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('Programme', 'Project', 'Funding', 'Pipeline', name='investment_type_enum'), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('coverage_area', sa.Text(), nullable=True),
    sa.Column('target_population', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_last_updated', sa.Date(), nullable=True),
    sa.Column('platform_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_period', sa.String(length=50), nullable=True),
    sa.Column('geographic_granularity', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'needs_review', name='inv_verification_enum'), nullable=False),
    sa.Column('freshness_status', sa.Enum('recent', 'stale', 'unknown', name='inv_freshness_enum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_investments_country_id'), ['country_id'], unique=False)

    op.create_table('infrastructure_data_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('official_coverage', sa.Enum('Low', 'Medium', 'High', name='coverage_level_enum'), nullable=False),
    sa.Column('nearest_facility_distance_km', sa.Float(), nullable=True),
    sa.Column('capacity_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_last_updated', sa.Date(), nullable=True),
    sa.Column('platform_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_period', sa.String(length=50), nullable=True),
    sa.Column('geographic_granularity', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'needs_review', name='data_verification_enum'), nullable=False),
    sa.Column('freshness_status', sa.Enum('recent', 'stale', 'unknown', name='freshness_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_data_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_data_points_country_id'), ['country_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('official_project_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('Planning', 'Approval', 'Tender', 'Construction', 'Completion', name='project_status_enum'), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.Column('linked_demand_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['linked_demand_cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('original_raw_input', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('channel', sa.Enum('text', 'voice', 'messaging', name='report_channel_enum'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_enum'), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('affected_group', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Unclustered', 'Clustered', name='report_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_citizen_id'), ['citizen_id'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('StillHappening', 'Improved', 'Worse', 'Resolved', name='verification_state_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_demand_cluster_id'), ['demand_cluster_id'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('joined', 'confirmed', 'evidence_added', name='contribution_type_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_demand_cluster_id'), ['demand_cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_report_id'), ['report_id'], unique=False)

    op.create_table('event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.Enum('Submitted', 'AIUnderstood', 'JoinedDemand', 'UnderReview', 'Decision', 'Implementation', 'Outcome', name='event_stage_enum'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('photo', 'video', 'audio', 'document', name='evidence_type_enum'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_to', sa.Enum('Report', 'DemandCluster', name='evidence_attached_to_enum'), nullable=False),
    sa.Column('attached_to_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_attached_to_id'), ['attached_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_report_id'), ['report_id'], unique=False)

    op.create_table('government_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_role', sa.Enum('mp', 'planning_officer', name='decision_actor_role_enum'), nullable=False),
    sa.Column('decision_type', sa.Enum('Prioritize', 'Defer', 'Deprioritize', 'NeedsValidation', 'Redirected', name='decision_type_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('linked_project_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_decisions_demand_cluster_id'), ['demand_cluster_id'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('before_indicator', sa.Text(), nullable=True),
    sa.Column('after_indicator', sa.Text(), nullable=True),
    sa.Column('impact_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AwaitingOutcomeData', 'Verified', name='outcome_status_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_project_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('government_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_decisions_demand_cluster_id'))

    op.drop_table('government_decisions')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_report_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_attached_to_id'))

    op.drop_table('evidence')
    op.drop_table('event_logs')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_report_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_demand_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_citizen_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_demand_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_citizen_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_citizen_id'))

    op.drop_table('reports')
    op.drop_table('projects')
    with op.batch_alter_table('infrastructure_data_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_data_points_country_id'))

    op.drop_table('infrastructure_data_points')
    with op.batch_alter_table('government_investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_investments_country_id'))

    op.drop_table('government_investments')
    with op.batch_alter_table('demographic_data_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demographic_data_points_country_id'))

    op.drop_table('demographic_data_points')
    op.drop_table('demand_clusters')
    op.drop_table('administrative_regions')
    op.drop_table('countries')
    op.drop_table('categories')
    # ### end Alembic commands ###
