"""add mplads state summary table

Revision ID: 6833efdb0680
Revises: af5171469711
Create Date: 2026-09-20 17:40:26.153302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6833efdb0680'
down_revision = 'af5171469711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mplads_state_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('lok_sabha_term', sa.String(length=40), nullable=False),
    sa.Column('mp_count', sa.Integer(), nullable=True),
    sa.Column('total_allocated', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_expenditure', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fund_utilization_pct', sa.Float(), nullable=True),
    sa.Column('works_completed', sa.Integer(), nullable=True),
    sa.Column('works_recommended', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_last_updated', sa.Date(), nullable=True),
    sa.Column('platform_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['administrative_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'lok_sabha_term', name='uq_mplads_region_term')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mplads_state_summaries')
    # ### end Alembic commands ###
