"""add whatsapp preferred_language

Revision ID: af5171469711
Revises: 13aacd383e2d
Create Date: 2026-09-20 15:15:11.950227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5171469711'
down_revision = '13aacd383e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_message_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_message_logs', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
