"""schema v2 geospatial and embeddings

Revision ID: e891866035d4
Revises: 64d29c027862
Create Date: 2026-08-22 04:17:18.783341

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = 'e891866035d4'
down_revision = '64d29c027862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centroid', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
        # Note: GeoAlchemy2 automatically creates idx_demand_clusters_centroid
        # (GIST index) when the GEOGRAPHY column is added.  The explicit
        # create_index call is omitted here to avoid a DuplicateTable error.
        batch_op.drop_column('centroid_wkt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centroid_wkt', sa.TEXT(), autoincrement=False, nullable=True))
        # Drop the GIST index that GeoAlchemy2 auto-created on upgrade.
        batch_op.drop_index('idx_demand_clusters_centroid', postgresql_using='gist')
        batch_op.drop_column('embedding')
        batch_op.drop_column('centroid')

    # ### end Alembic commands ###
